### PR TITLE
Make class open instead of public so 3rd party projects can extend it.

### PR DESCRIPTION
**Pull request by noordawod**

### CODE REVIEW

**Comment by noordawod** [comment]
In Swift 4 (not sure about 3), public classes cannot be extended. They must be declared open.

**Comment by ldiqual** [comment]
@noordawod Sorry for the delay on this.

We're about to make `FlatButton / PressableButton / CustomPressableButton` open but we're conflicted about whether we should make the properties / methods open too. The main thing is that it will be very easy to forget calling `super`, which will cause the button to not update properly (because the underlying `updateImageInsets / updateBackgroundImages` won't be called). This might create a significant maintenance workload with users opening github issues about this, so I think we should give it a bit more thoughts.

What's your usecase here? Is there a way you could extend the class but not the properties / methods?

**Comment by noordawod** [comment]
The use case is to be able to override the properties really. But if you have another way how to do it, then by all means.

Remember that if developers mess up, they will have to read the docs. So be sure to mention it in big letters then, and I think having it open should be alright.

**Comment by ldiqual** [comment]
@noordawod You might be interested in https://github.com/TakeScoop/SwiftyButton/pull/18 which we'll merge + publish now. Baby steps to extensibility until we think more about what it means to have open methods / properties. Sorry for the delay on this

**Comment by noordawod** [comment]
Thanks.

**Pull request closed without merging**
